{% set version = "1.2.2" %}

package:
  name: autodoc-traits
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/autodoc-traits/autodoc_traits-{{ version }}.tar.gz
  sha256: a42bc8a78fe95cffb84bdb30b301368347442666ae6f9543304c566761d6a91c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sphinx >=4
    - traitlets >=4

test:
  source_files:
    - tests
  imports:
    - autodoc_traits
  commands:
    - pip check
    # skipped on windows due to unix-style paths in tests
    - pytest -vv --cov=autodoc_traits --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100  # [unix]
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://pypi.org/project/autodoc-traits
  summary: Sphinx extension to autodoc traitlets
  dev_url: https://github.com/jupyterhub/autodoc-traits
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
