{% set version = "1.2.2" %}

package:
  name: autodoc-traits
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/autodoc-traits/autodoc_traits-{{ version }}.tar.gz
  sha256: a42bc8a78fe95cffb84bdb30b301368347442666ae6f9543304c566761d6a91c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - sphinx >=4
    - traitlets >=4

test:
  source_files:
    - tests
  imports:
    - autodoc_traits
  commands:
    - pip check
    # skipped on windows due to unix-style paths in tests
    - coverage run --branch --source=autodoc_traits -m pytest -vv --color=yes --tb=long  # [unix]
    - coverage report --show-missing --skip-covered --fail-under=100                     # [unix]
  requires:
    - coverage
    - pip
    - pytest

about:
  home: https://pypi.org/project/autodoc-traits
  summary: Sphinx extension to autodoc traitlets
  dev_url: https://github.com/jupyterhub/autodoc-traits
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
